### ISSUE TITLE
can you please help in. configuration by reading in readme

### ISSUE THREAD

**Issue by IshanSingla** [AndrewLaneX/GibHugBot#2]

**Comment by vrumger** [comment]
## `.env`
- `PORT` - the port your webhook server should run on
- `BOT_TOKEN` - your telegram bot token
- `MONGO_URI` - your mongo uri string
- `GITHUB_CLIENT_ID` - your [github oauth app] client id
- `GITHUB_CLIENT_SECRET` - your [github oauth app] secret
- `GITHUB_WEBHOOK_DOMAIN` - the domain your github webhook runs on

[github oauth app]: https://github.com/settings/developers

**Comment by IshanSingla** [comment]
How to setup webhoock

**Comment by vrumger** [comment]
The bot will do it automatically when someone sets an integration.
